Asp.NetMVCEducation.NETFramework/Controllers/Mvc09ViewToControllerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVCEducation.NETFramework.Controllers
{
    public class Mvc09ViewToControllerController : Controller
    {
        // GET: Mvc09ViewToController
        public ActionResult Index(string txtAra) // Mvc de ındex metodu içerisine bu şekilde parametre ekleyerek ön yüzden gönderilen veriyi yakalayabiliyoruz. Dikkat! eşleşme sağlanabilmesi için ön yüzdeki elemanın name bilgisi ile buradaki değişken bilgisinin aynı isimde olması lazım yoksa eşleşmez!!!
        {
            ViewBag.GetVerisi = "Aranan kelime : " + txtAra;
            return View();
        }
        [HttpPost] // aşağıdaki metodun sadece post işlemlerinde çalışmasını sağlar
        public ActionResult Index(string text1, string ddlListe, bool cbOnay)
        {
            //1. yöntem parametrelerden gelen veri;
            ViewBag.Mesaj = "textboxdan gelen veri : " + text1;
            ViewData["Vdata"] = "checkboxdan gelen veri : " + cbOnay;
            TempData["Tdata"] = "listboxdan gelen veri : " + ddlListe;

            //2. yöntem Request.Form ile sayafadaki elementlerden veri alma
            var txt = Request.Form["text1"];
            var ddl = Request.Form["ddlListe"];
            //var chb = Request.Form["cbOnay"]; true,false dönüyor
            var chb = Request.Form.GetValues("cbOnay")[0];

            ViewBag.Mesaj2 = "textboxdan gelen veri 2 : " + txt;
            ViewData["Vdata2"] = "checkboxdan gelen veri 2 : " + chb;
            TempData["Tdata2"] = "listboxdan gelen veri 2 : " + ddl;

            return View();
        }
    }
}

Asp.NetMVCEducation.NETFramework/Views/Mvc09ViewToController/Index.cshtml
@{
    ViewBag.Title = "Mvc View den Controller a Veri Gönderme";
}

<h2>Mvc View den Controller a Veri Gönderme</h2>

<h3>GET Metoduyla veri gönderme</h3>

<div>
    @using (Html.BeginForm("Index", "Mvc09ViewToController", FormMethod.Get))
    {
        @Html.TextBox("txtAra")
        <input type="submit" value="Ara" />
    }
</div>

<p>
    Get metoduyla formdan butona basılırsa veriler adres çubuğu üzerinden get metoduna QueryString yöntemiyle iletilir. Adres çubuğundaki ?txtAra=monitör kısmındaki txtAra ilgili input un name değeridir, monitör ise bu parametrenin taşıdığı değer.
</p>

@ViewBag.GetVerisi

<hr />

<h2>MVC View dan Controller a Post Metodu ile veri gönderme</h2>

@{
    SelectListItem[] liste = new SelectListItem[3]
    {
       new SelectListItem() { Text="Bilgisayar" },
       new SelectListItem() { Text="Monitör"  },
       new SelectListItem() { Text="Tablet" }
                                            };
    <div>
        @using (Html.BeginForm())
        {
            @Html.TextBox("text1")
            <hr />
            @Html.DropDownList("ddlListe", liste)
            <hr />
            @Html.CheckBox("cbOnay") <label>Onaylıyorum</label>
            <hr />
            <input type="submit" value="Gönder" />
        }
    </div>

    <hr />

    if (IsPost) // Eğer sayfa post edildiyse
    {
        @ViewBag.Mesaj
        <hr />
        @ViewData["Vdata"]
        <hr />
        @TempData["Tdata"]
        <hr />

        <h3>2. yöntem (Request.Form) ile </h3>

        @ViewBag.Mesaj2
        <hr />
        @ViewData["Vdata2"]
        <hr />
        @TempData["Tdata2"]
    }

}